services:
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    restart: always
  backend:
    build: .
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    restart: always
