/**
 * @fileoverview gRPC-Web generated client stub for Game
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.6.1
// source: src/proto/game.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as src_proto_game_pb from '../../src/proto/game_pb'; // proto import: "src/proto/game.proto"


export class StateUpdateClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetIncrementalMapUpdate = new grpcWeb.MethodDescriptor(
    '/Game.StateUpdate/GetIncrementalMapUpdate',
    grpcWeb.MethodType.SERVER_STREAMING,
    src_proto_game_pb.IncrementalMapUpdateRequest,
    src_proto_game_pb.IncrementalMapUpdateResponse,
    (request: src_proto_game_pb.IncrementalMapUpdateRequest) => {
      return request.serializeBinary();
    },
    src_proto_game_pb.IncrementalMapUpdateResponse.deserializeBinary
  );

  getIncrementalMapUpdate(
    request: src_proto_game_pb.IncrementalMapUpdateRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<src_proto_game_pb.IncrementalMapUpdateResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/Game.StateUpdate/GetIncrementalMapUpdate',
      request,
      metadata || {},
      this.methodDescriptorGetIncrementalMapUpdate);
  }

  methodDescriptorGetMiscGameStateUpdate = new grpcWeb.MethodDescriptor(
    '/Game.StateUpdate/GetMiscGameStateUpdate',
    grpcWeb.MethodType.SERVER_STREAMING,
    src_proto_game_pb.MiscStateUpdateRequest,
    src_proto_game_pb.MiscStateUpdateResponse,
    (request: src_proto_game_pb.MiscStateUpdateRequest) => {
      return request.serializeBinary();
    },
    src_proto_game_pb.MiscStateUpdateResponse.deserializeBinary
  );

  getMiscGameStateUpdate(
    request: src_proto_game_pb.MiscStateUpdateRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<src_proto_game_pb.MiscStateUpdateResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/Game.StateUpdate/GetMiscGameStateUpdate',
      request,
      metadata || {},
      this.methodDescriptorGetMiscGameStateUpdate);
  }

}

